numero  = input("Anna kokonaisluku:")
number = input("Anna toinen kokonaisluku:")
print("Summa:", number + numero)
print("Erotuksen:", number - numero)
print("Tulon:", number*numero)
print("Osamaaran:",number/numero)